server:
  port: 8500
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: student-service   
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spr810
    username: root
    password: ajay
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true     